---
name: Workflow

on:
  push:
  workflow_dispatch:

jobs:
  init:
    uses: PhilippAuch/workflows/.github/workflows/init.yaml@main

  test:
    uses: PhilippAuch/workflows/.github/workflows/testNode.yaml@main

  # sonar:
  #   uses: PhilippAuch/workflows/.github/workflows/sonar.yaml@main
  #   needs: test
  #   with:
  #     branch-name: '${{ inputs.branch-name }}'
  #     sonar-project-key: 'philipp-auch-de_jiramanager'
  #   secrets:
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish:
    needs: test
    uses: PhilippAuch/workflows/.github/workflows/publishRelease.yaml@main
