---
name: Workflow

on:
  push:
  workflow_dispatch:

jobs:
  init:
    uses: PhilippAuch/workflows/.github/workflows/init.yaml@main

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - run: npm install
      - run: npm run test
# sonar:
#   uses: PhilippAuch/workflows/.github/workflows/sonar.yaml@main
#   with:
#     branch-name: '${{ inputs.branch-name }}'
#     sonar-project-key: 'philipp-auch-de_jiramanager'
#   secrets:
#     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
