---
name: Workflow

on:
  push:
  workflow_dispatch:

jobs:
  init:
    uses: PhilippAuch/workflows/.github/workflows/init.yaml@main

  test:
    uses: PhilippAuch/workflows/.github/workflows/testNode.yaml@main

  publish:
    needs: test
    uses: PhilippAuch/workflows/.github/workflows/publishRelease.yaml@main
